In [ ]:
import numpy as np

# Task no 1
def function1():
    # create 2d array from 1,12 range 
    # dimension should be 6row 2 columns  
    # and assign this array values in x values in x variable
    # Hint: you can use arange and reshape numpy methods  

  array =  np.arange(1,13).reshape((6,2)) 
  x = array
  return x

function1()  

 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
def function2():
    #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape 
  
    array = np.arange(10, 37, dtype=float).reshape((3, 3, 3)) #wrtie your code here


    return array
function2()    

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [ ]:
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
              #wrtie your code here
    condition = np.mod(a, 35)==0
    x = np.extract(condition, a)
    return x

function3()    

array([ 35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980])

In [ ]:
def function4():
    #Swap columns 1 and 2 in the array arr.

    arr = np.arange(9).reshape(3,3)

    #wrtie your code here
    return arr

function4()    

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
def function5():
    #Create a null vector of size 20 with 4 rows and 5 columns with numpy function

    z = np.zeros([5, 4]) #wrtie your code here

    return z

function5()    

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively

    arr = np.zeros(10)                             #wrtie your code here
    arr[5]= 10
    arr[8]= 20

    return arr

function6()    

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.])

In [ ]:
def function7():
    #  Create an array of zeros with the same shape and type as X. Dont use reshape method
    x = np.zeros(4, dtype=np.int64)     #write your code here
  
    return  x   
function7()

array([0, 0, 0, 0])

In [ ]:
#task8

def function8():
    # Create a new array of 2x5 uints, filled with 6.

    x = np.full((2, 5), 6, dtype = np.unit) #write your code here
    return x
function8()

AttributeError: ignored

In [ ]:
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.

    a = np.arange(2, 101, 2) # write your code here

    return a
function9()

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [81]:
#task10
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.

    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = arr - brr  # write your code here 

    return subt

function10()

array([[2, 1, 0],
       [3, 2, 1],
       [4, 3, 2]])

In [97]:
#task11
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.

    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    odd_values = (arr %2 == 1) 
    arr[odd_values] = -1
    ans = arr

    return ans

function11()    

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [111]:
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept

    arr = np.array([1,2,3])
     
    ans =                     #write your code here 

    return ans
function12()

array([1, 2, 1, 1, 2, 3, 1, 2, 3])

In [130]:
#task13
def function13():
    # Set a condition which gets all items between 5 and 10 from arr.


    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    ans = arr.where((arr < 5) & (arr > 10))                       #write your code here 

    return ans
     
function13()   

AttributeError: ignored

In [146]:
def function14():
    # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method


    arr = np.arange(10, 34, 1).reshape((4, 6))                               #write reshape code
    ans = np.array_split(arr, 4)                                                    #write your code here 

    return ans

function14()

[array([[10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21]]),
 array([[22, 23, 24, 25, 26, 27]]),
 array([[28, 29, 30, 31, 32, 33]])]

In [151]:
#task15
def function15():
    #Sort following NumPy array by the second column


    arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
    ans = sorted(arr, key=lambda a_entry: a_entry[1]) 
        #write your code here 

    return ans
function15()

[array([-4,  1,  7]), array([ 8,  2, -2]), array([6, 3, 9])]

In [160]:
#task16
def function16():
    #Write a NumPy program to join a sequence of arrays along depth.


    x = np.array([[1], [2], [3]]) 
    y = np.array([[2], [3], [4]]) 
    ans = np.vstack((x, y)) #write your code here 

    return ans
function16()

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [161]:
#Task17
def function17():
    # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
    arr = np.arange(1,10*10+1).reshape((10,10))

    return arr.where((arr%3 == yes ) & (arr %2 == No) )          # Write Your Code HERE
function17()

AttributeError: ignored

In [181]:
#Task18
def function18():
    # count values of "students" are exist in "piaic"
    piaic = np.arange(100)
    students = np.array([5,20,50,200,301,7001])
    x = np.isin(students, piaic)      
    return x
function18()

array([ True,  True,  True, False, False, False])