In [ ]:
import numpy as np

np.__version__


'1.19.4'

In [ ]:
#method__1

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#method_2

a.shape

(3, 5)

In [ ]:
#method_3

a.ndim


2

In [ ]:
#method_4

a.dtype.name


'int64'

In [ ]:
#method_5

a.itemsize


8

In [ ]:
#method_6

a.size


15

In [ ]:
#method_7

a.item

<function ndarray.item>

In [ ]:
#method_8

type(a)

numpy.ndarray

In [ ]:
#method_9


b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [ ]:
 #method_10

 a = np.array([2, 3, 4])
 
 a, type(a), a.dtype


(array([2, 3, 4]), numpy.ndarray, dtype('int64'))

In [ ]:
#method_11

b = np.array([2.5, 3.8, 4.3])
 
b, type(b), b.dtype

(array([2.5, 3.8, 4.3]), numpy.ndarray, dtype('float64'))

In [ ]:
#method_12


b = np.array([(1.5, 3, 3), (4, 6, 8)])

b, b.dtype

(array([[1.5, 3. , 3. ],
        [4. , 6. , 8. ]]), dtype('float64'))

In [ ]:
#method_13

c = np.array([[1,2], [3,4]], dtype=complex)

c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
#method_14

d = np.zeros((3, 4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#method_15

np.ones((2, 5, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
#method_16

np.empty((2, 5))

array([[3.62179446e-316, 2.58883487e-312, 2.41907520e-312,
        2.14321575e-312, 8.48798317e-313],
       [1.08221785e-312, 6.79038653e-313, 8.70018275e-313,
        2.02566915e-322, 0.00000000e+000]])

In [ ]:
#method_17

np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [ ]:
#method_18

np.arange(.5, 15, 3)

array([ 0.5,  3.5,  6.5,  9.5, 12.5])

In [ ]:
#method_19

from numpy import pi

np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
#method_20

x = np.linspace(0, 2*pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [ ]:
#method_21

f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [ ]:
#method_22

np.empty_like((4, 6))

array([       0, 67456320])

In [ ]:
#method_23

np.ones_like((3, 8))

array([1, 1])

In [ ]:
#method_24

np.zeros_like((2, 8))

array([0, 0])

In [ ]:
#method_25

a = np.array([20, 30, 0, 50])
b = np.arange(4)

a, b

c = b-a 

c

array([-20, -29,   2, -47])

In [ ]:
#method_26

b**2

array([0, 1, 4, 9])

In [ ]:
#method__27

10*np.sin(a)

array([ 9.12945251, -9.88031624,  0.        , -2.62374854])

In [ ]:
#method_28

a>35, a

(array([False, False, False,  True]), array([20, 30,  0, 50]))

In [ ]:
#method__29

A = np.array([[1,1],
             [0,1]])
B = np.array([[3,4],
             [0,8]])

A*B

array([[3, 4],
       [0, 8]])

In [ ]:
#method__30

A @ B

array([[ 3, 12],
       [ 0,  8]])

In [ ]:
#method__30

A.dot(B)

array([[ 3, 12],
       [ 0,  8]])

In [ ]:
#method__31

rg = np.random.default_rng(1)

a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
#method__32

b += a

b

array([[6.51182162, 6.9504637 , 6.14415961],
       [6.94864945, 6.31183145, 6.42332645]])

In [ ]:
#method__33

b = np.linspace(0, pi, 3)

b.dtype.name

'float64'

In [ ]:
#method__34

c = a+b

c




array([[3.        , 4.57079633, 6.14159265],
       [3.        , 4.57079633, 6.14159265]])

In [ ]:
#method__35

d = np.exp(c*1j)

d


array([[-0.9899925 +0.14112001j, -0.14112001-0.9899925j ,
         0.9899925 -0.14112001j],
       [-0.9899925 +0.14112001j, -0.14112001-0.9899925j ,
         0.9899925 -0.14112001j]])

In [ ]:
#method__36

d.dtype.name

'complex128'

In [ ]:
#method__37

a = rg.random((2, 3))
a

array([[0.20345524, 0.26231334, 0.75036467],
       [0.28040876, 0.48519097, 0.9807372 ]])

In [ ]:
#method__38

a.sum()

2.962470185966965

In [ ]:
#method__39

a.min()

0.20345524067614962

In [ ]:
#method__40

a.max()

0.9807371998012386

In [ ]:
#method__41


b = np.arange(12).reshape(3, 4)
b.sum(axis=0)

array([12, 15, 18, 21])

In [ ]:
#method__42

b.min(axis=1)

array([0, 4, 8])

In [ ]:
#method__43

b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [ ]:
#method__44

B = np.arange(3)
np.exp(B) 

array([1.        , 2.71828183, 7.3890561 ])

In [ ]:
#method__45

np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [ ]:
#method__46

C = np.array([1, 5, 6])

np.add(B, C)

array([1, 6, 8])

In [ ]:
#method__47

np.all(B)

False

In [ ]:
#method__48

np.average(B)

1.0

In [ ]:
#method__49


np.sort(B)

array([0, 1, 2])

In [ ]:
#method__50

np.invert(C)

array([-2, -6, -7])